version: "3.7"
services:
  docker-dns:
    container_name: dns
    image: jpillora/dnsmasq
    hostname: dns
    volumes:
      - ./dnsmasq.conf/:/etc/dnsmasq.conf
    ports:
      - 53:53/udp
      - 53:53/tcp
    expose:
      - 53
      - 8080
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      traefik:
        ipv4_address: 172.19.0.53
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dns.entrypoints=web"
      - 'traefik.http.routers.dns.rule=Host(`dns.home.com`)'
      - "traefik.http.services.dns.loadbalancer.server.port=8080"
networks:
  traefik:
    external: true
