---
version: "2"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./emby:/config
      - /home/golden/Downloads/.movie:/download
      - /home/golden/Videos:/movies
    expose:
      - 8096
    ports:
      - 8096:8096
    restart: unless-stopped
    dns: 172.18.1.53
    networks:
      - traefik 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.entrypoints=web"
      - 'traefik.http.routers.emby.rule=Host(`emby.home.com`)'
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      #- RUN_OPTS=run options here #optional
    volumes:
      - ./jackett:/config
      - /home/golden/Downloads:/data
    restart: unless-stopped
    expose:
      - 9117
    networks:
      - traefik
    dns: 172.18.1.53
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.entrypoints=web"
      - 'traefik.http.routers.jackett.rule=Host(`jackett.home.com`)'
      - "traefik.http.services.jackett.loadbalancer.server.port=8117"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr:/config
      - /home/golden/Downloads:/data
    expose: 
      - 7878
    restart: unless-stopped
    networks:
      - traefik
    dns: 172.18.1.53
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=web"
      - 'traefik.http.routers.radarr.rule=Host(`radarr.home.com`)'
      - "traefik.http.services.radarr.loadbalancer.server.port=8080"
networks:
  traefik:
    external: true
