version: '3'
services:
  traefik:
    restart: always
    image: traefik:v2.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - '80:80'
      - '8080:8080'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - 'traefik.http.routers.traefik.rule=Host(`traefik.home.com`)'
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
        #- ./acme.json:/acme.json
    networks:
      - traefik 
networks:
  traefik:
    external: true
