---
version: "2"
services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    networks: 
      - traefik
    expose:
      - 8112
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=timezone
    volumes:
      - /home/golden/.config/deluge/:/config
      - /data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.entrypoints=web"
      - 'traefik.http.routers.deluge.rule=Host(`deluge.home.com`)'
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
networks:
  traefik:
    external: true
