version: '3'

services:
        #  proxy:
        # build: nginx/
        #container_name: "portainer-proxy"
        #ports:
        #- "80:80"
        #networks:
        #- local

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - traefik
    labels:
      - 'traefik.enable=false'
    restart: always

  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer-app"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --templates http://templates/templates.json
    networks:
      - traefik
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
      - 'traefik.http.routers.portainer.rule=Host(`portainer.home.com`,`p.home.com`)'
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=false'
    restart: always

networks:
  traefik:
    external: true
