# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hgp
    volumes:
      - ./data:/var/lib/mysql
    user: 1000:1000
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
