---
version: "3.7"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
    volumes:
      - /home/golden/.config/transmission-daemon:/config
      - /data:/data
      - /home/golden/Downloads/:/watch
    expose:
      - 9091
      - 51413
        #ports:
        # - 9091:9091
        #- 51413:51413
        #- 51413:51413/udp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=9091"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:transmission.home.com,trans.home.com"
      - "traefik.frontend.entryPoints=http"
networks:
  traefik:
    external: true
