---
version: "3.7"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
    volumes:
      - /home/golden/.config/transmission-daemon:/config
      - /data:/data
      - /home/golden/Downloads/:/watch
    expose:
      - 9091
      - 51413
        #ports:
        # - 9091:9091
        #- 51413:51413
        #- 51413:51413/udp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=web"
      - 'traefik.http.routers.transmission.rule=Host(`transmission.home.com`,`trans.home.com`)'
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
networks:
  traefik:
    external: true
