---
version: "3.7"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
    volumes:
      - ./config:/config
      - /home/golden/Downloads/:/data
      - /home/golden/Downloads/.movie:/download
      - /home/golden/Videos/:/movie
    expose:
      - 9091
      - 51413
        #ports:
        # - 9091:9091
        #- 51413:51413
        #- 51413:51413/udp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=web"
      - 'traefik.http.routers.transmission.rule=Host(`transmission.home.com`,`trans.home.com`)'
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
  transmission-tracker-add:
    image: andrewmhub/transmission-tracker-add    
    container_name: transmission-tracker-add 
    # dns: 172.19.0.53
    networks:
      - traefik
    restart: unless-stopped
    environment:
      - HOSTPORT=transmission:9091
      - TR_AUTH=":"
      - TORRENTLIST=https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt
networks:
  traefik:
    external: true
